FROM node:20-alpine

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./backend/
RUN npm ci --prefix backend

COPY backend ./backend
COPY mock ./mock

EXPOSE 1883
CMD ["node", "backend/src/index.js"]
